# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a482deaef36c9ffa2aa5f75e9539d7b5531ee1cd736234c62bea1b427c508ce00920cbf98ec207d99e9c341e27f4fd2bffb5012c413aea3e775db7b5ca900db3

test:
  secret_key_base: aa987862c6c47e7c33e5a8359d14ca2003083e1ff2b03a16706903cb6d888c9ef30e3a2d272a433ada4cffca94b62204765a2084011e1a2f89c2eab2945d48e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
